% Hack fix empty TMap_half fields in PlaceMaps.mat by replacing with
% TMap_half from PlaceMaps_rot_to_std.mat

%% Re-run screwed up sessions for PFA
PFA_batch(MD(G45_square_sesh(1)),'201a - 2015',1,'rotate_to_std',1,'calc_half',1);
PFA_batch(MD(G45_square_sesh(2)),'201a - 2015',1,'rotate_to_std',0,'calc_half',0);

%% Run it
sesh_index = [G48_square_sesh G48_oct_sesh];

for j = 1:length(sesh_index)
   ChangeDirectory_NK(MD(sesh_index(j)))
   load PlaceMaps_rot_to_std
   save('PlaceMaps_rot_to_std_archive.mat','x', 'y', 't', 'xOutline', 'yOutline', 'speed','minspeed', ...
       'FT', 'TMap','TMap_gauss', 'TMap_unsmoothed', 'RunOccMap', 'OccMap', ...
       'SpeedMap', 'RunSpeedMap', 'NeuronImage', 'NeuronPixels',...
       'cmperbin', 'pval', 'Xbin', 'Ybin', 'FToffset', 'FToffsetRear', 'isrunning',...
       'Xedges', 'Yedges','exclude_frames','aviFrame','TMap_half','pval_half',...
       'pvalI','Pix2Cm','-v7.3');
 
   load PlaceMaps
   save('PlaceMaps_archive.mat','x', 'y', 't', 'xOutline', 'yOutline', 'speed','minspeed', ...
       'FT', 'TMap','TMap_gauss', 'TMap_unsmoothed', 'RunOccMap', 'OccMap', ...
       'SpeedMap', 'RunSpeedMap', 'NeuronImage', 'NeuronPixels',...
       'cmperbin', 'pval', 'Xbin', 'Ybin', 'FToffset', 'FToffsetRear', 'isrunning',...
       'Xedges', 'Yedges','exclude_frames','aviFrame','TMap_half','pval_half',...
       'pvalI','Pix2Cm','-v7.3');
   
   load('PlaceMaps_rot_to_std.mat','TMap_half')
   save('PlaceMaps.mat','x', 'y', 't', 'xOutline', 'yOutline', 'speed','minspeed', ...
       'FT', 'TMap','TMap_gauss', 'TMap_unsmoothed', 'RunOccMap', 'OccMap', ...
       'SpeedMap', 'RunSpeedMap', 'NeuronImage', 'NeuronPixels',...
       'cmperbin', 'pval', 'Xbin', 'Ybin', 'FToffset', 'FToffsetRear', 'isrunning',...
       'Xedges', 'Yedges','exclude_frames','aviFrame','TMap_half','pval_half',...
       'pvalI','Pix2Cm','-v7.3');
end